= Simple Interfaces in RHEL based distribtions
:author:Mark Lamourine <markllama@gmail.com>
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

'''

WARNING: This is an incomplete draft document

''''

In Red Hat Enterprise Linux and Fedora and their derivative
distributions, network interfaces are initialized from configuration
files in `/etc/sysconfig/network-scripts`

They can also be managed dynamically by _Network-Manager_.  This
document focuses only on the configuration files and the simplest CLI
network management commands, `ifup`, `ifdown` and `ip`.
Network-Manager will be the topic for another day.

== `ifup`, `ifdown` and `ip`

The most common operation on a network interface is to initialize it
or shut it down.  Red Hat systems have two special commands for
this.

* `ifup <interface>`- bring up the interface
* `ifdown <interface>` - shut down the interface

The interface names are strings matching the interface listed by `ip link`.
They also correspond to files at
`/etc/sysconfig/network-scripts/ifcfg-<interface>`.




The `ip` command is common to RHEL and Ubuntu distributions.  It's
also a big enough topic for it's own brownbag talk. I'll leave that
for another time.


=== `if{up,down}-*` scripts


The `/etc/sysconfig/network-scripts` directory contains all of the
scripts that are used to manage the interfaces.  There is an `ifup-*`
and `ifdown-*` for each type of interface. You can scan these to see
how the process works and what variables are available, but you will
never invoke them directly.


== `ifcfg-*` network definition files

Each physical and virtual interface on a RHEL based system is
configured with a file named `ifcfg-<interface>` where _<interface>_
is the name of the interface as reported by `ip link`. The file is a
shell script fragment with a set of environment variable
assignments.

For example, a simple ethernet interface configuration file might
contain something like this

.`ifcfg-eno1` sample
----
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=no
IPV4_FAILURE_FATAL=no
IPV6INIT=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=eno1
UUID=f6f93648-b714-409c-b87b-cd214e6f4b30
DEVICE=eno1
ONBOOT=yes
IPADDR=172.16.2.2
PREFIX=24
----

If you are at all familiar with linux networking these should be
fairly self-explanatory. In most cases you will not need to change
these values after the system is initialized.  There are also
additional variables that are used to configure things like bridges
and bonded interfaces. These will be the topic for another day.

== `ifcfg-*` environment variables

This is a sample of the commmon settings you will find in simple
interface configurations. These can be for either physical or virtual
interfaces.

The variabled shown here are just the most commonly set on Ethernet
interfaces. A complete list with detailed descriptions can be found in
documents listed in the References.

=== Interface Identification

These variables define the interface itself. They specify the which
interface to configure.

TYPE=Ethernet::
  These values apply to Ethernet interfaces only

DEVICE=<name>::
  Name is a string identifying the physical interface

NAME=<name>::
  Assign a label to the interface. Almost always the same as DEVICE
  
NM_CONTROLLED=[yes|no]::
  Does Network-Manager control this interface? Probably no on servers.

=== Basic Configuration

ONBOOT=[yes|no]::
  Start this interface on boot? Probably yes.

BOOTPROTO=[none|dhcp|bootp]::
  Almost certainly none. +
  You may sometimes see _static_. This is the same as _none_. 

=== IPv4 Configuration

IPADDR=<ipv4_address>::
  A dotted quad IPv4 address string

PREFIX=n::
  A CIDR mask number.  0-32 +
  You may occasionally see `NETMASK` with a dotted quad. This is deprecated.

GATEWAY=<ipv4_address>::
  A dotted quad IPv4 address in the broadcast domain defined by
  `IPADDR` and `PREFIX`
  
PEERDNS=[yes|no]::
  Allow NetworkManager to update `/etc/resolv.conf`. +
  Should generally be _no_

DNS[n]=<ipv4_address>::
  An IPv4 address of a nameserver.
  To set more than one nameserver, use n=1,2,3  

=== IPv6 Configuration

IPv6 configuration is out of scope, but you will often see these in an
Ethernet configuration file. Unless the systems are explictly using
IPv6, `IPV6INIT` should be 'no' and the rest are then NO-OPs. 

* IPV6INIT=[yes|no]
* IPV6_AUTOCONF=[yes|no]
* IPV6_DEFROUTE=[yes|no]
* IPV6_FAILURE_FATAL=[yes|no]
* IPV6_ADDR_GEN_MODE=stable-privacy

== References

* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-networkscripts-interfaces[RHEL Interface Configuration Files]
