:source-highlighter: pygments
:toc:
:toc-placement!:

== Subscription Manager Concepts

`subscription-manager` is the tool Red Hat uses to control access to
premium software packages and updates. It serves three functions for
the sysadmin.

* register the host with Red Hat
* attach a subscription (software entitlement)
* enable YUM repositories provided by the subscription.

Each step serves to build a connection between the host and the RPM
repositories.

toc::[]

=== Register

Registration associates the host to an account on the Red Hat Network.
When complete, Red Hat is aware of the host and that you own it, but
it is not yet able to get software or updates.

Once a host is registered you can query the subscriptions that are
available. The next step is to attach the host to a subscription.

=== Attach

Attachment binds the registered host to a software subscription and
consumes one or more entitlements. This step tells Red Hat that you
mean to use a collection of software on this host and configures the
host to be able to see the repositories that this collection contains.

A unit of subscription is called a _pool_ and a pool is idenitified
with a _pool-id_ that is a long hash string.


=== Repos

A subscription typically provides a number of software
repositories. `subscription-manager` allows you to query what
repositories are available from the attached subscriptions and their
enablement status. In some ways this mirrors the behavior of
`yum repolist` . 

== Register host with Red Hat subscription service


=== Register with Customer Portal (username/password)

.Register Host with username/password
[literal,subs="verbatim,quotes"]
----
*subscription-manager register --username <username> --password <password>*
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: e3c6b7ba-83fa-4af8-8ef9-10aa6af2dd2e
The registered system name is: markllama-rhel7
----

=== Register with Satellite (org/activationkey)

.Register Host with org and activation key
[literal,subs="verbatim,quotes"]
----
*subscription-manager register --org <org name> --activationkey <key string>*
----

== Subscription Management

=== List available subscriptions (with pool ids)

.List Subscriptions and Pool IDs
[literal,subs="verbatim,quotes"]
----
*subscription-manager list --available | grep 'Name\|ID'*
Subscription Name:   60 Day Self-Supported Red Hat OpenStack Platform Preview
Pool ID:             8a85f99b6b498682016ba4f2722c4d98
Subscription Name:   Red Hat Developer Subscription
Pool ID:             8a85f9996ae5df64016b1fd8ff1f791c
----

=== Attach to a subscription


.Attach to a subscription
[literal,subs="verbatim,quotes"]
----
*subscription-manager attach --pool 8a85f9996ae5df64016b1fd8ff1f791c*
Successfully attached a subscription for: Red Hat Developer Subscription
----

== Repo Management

=== Listing repositories


.List enabled repositories
[literal,subs="verbatim,quotes"]
----
*subscription-manager repos --list-enabled | grep -A1 'Repo ID'*
Repo ID:   rhel-7-server-rpms
Repo Name: Red Hat Enterprise Linux 7 Server (RPMs)
----

 * `--list`
 * `--list-enabled`
 * `--list-disabled`

=== Enable/Disable repositories

==== Disable all repositories

.Disable all repositories
[literal,subs="verbatim,quotes"]
----
*subscription-manager repos --disable='*'*
Repository 'rhel-7-server-dotnet-debug-rpms' is disabled for this system.
Repository 'rhel-7-server-satellite-tools-6.2-rpms' is disabled for this system.
Repository 'rhel-7-server-v2vwin-1-debug-rpms' is disabled for this system.
...
----

==== Enable a set of repositories

.Enable a set of repositories
[literal,subs="verbatim,quotes"]
----
*subscription-manager repos \
  --enable rhel-7-server-rpms \
  --enable rhel-7-server-supplementary-rpms \
  --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-extras-rpms*
Repository 'rhel-7-server-rpms' is enabled for this system.
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
Repository 'rhel-7-server-supplementary-rpms' is enabled for this system.
Repository 'rhel-7-server-extras-rpms' is enabled for this system.
----

=== Yum tools for repo managment

The `subscription-manager repos` command simply manipulates the
`/etc/yum.repos.d/redhat.repo` file. If you are more comfortable with
the yum commands for repository control you can use them
interchangably with `subscription-manager`

* yum repolist
* yum-config-manager


== Appendix: Disable and remove RHN if needed

If the host you're working on is subscribed by traditional RHN (as is
the commercial cloud VM I'm using to demo this), disable that before beginning.

.Disable RHN Registration
[literal,subs="verbatim,quotes"]
----
*mv /etc/sysconfig/rhn/systemid /etc/sysconfig/rhn/disable.systemid
sed -i -e '/^enabled =/s/1/0/' /etc/yum/pluginconf.d/rhnplugin.conf*
----
== References

* https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/rhsm/index[USING AND CONFIGURING RED HAT SUBSCRIPTION MANAGER]
* https://access.redhat.com/solutions/253273[How to register and subscribe a system to the Red Hat Customer Portal using Red Hat Subscription-Manager]

