:source-highlighter: pygments

== Subscription Manager Concepts

`subscription-manager` is the tool Red Hat uses to control access to
premium software packages and updates. It serves three functions for
the sysadmin.

* register the host with Red Hat
* attach a subscription (software entitlement)
* enable YUM repositories provided by the subscription.

Each step serves to build a connection between the host and the RPM
repositories.

=== Register

Registration associates the host to an account on the Red Hat Network.
When complete, Red Hat is aware of the host and that you own it, but
it is not yet able to get software or updates.

Once a host is registered you can query the subscriptions that are
available. The next step is to attach the host to a subscription.

=== Attach

Attachment binds the registered host to a software subscription and
consumes one or more entitlements. This step tells Red Hat that you
mean to use a collection of software on this host and configures the
host to be able to see the repositories that this collection contains.

A unit of subscription is called a _pool_ and a pool is idenitified
with a _pool-id_ that is a long hash string.


=== Repos

A subscription typically provides a number of software
repositories. `subscription-manager` allows you to query what
repositories are available from the attached subscriptions and their
enablement status. In some ways this mirrors the behavior of
`yum repolist` . 

== Preparation of RHEL image - disable and remove RHN if needed

If the host you're working on is subscribed by traditional RHN (as is
the commercial cloud VM I'm using to demo this), disable that before beginning.

.Disable RHN Registration
[literal,subs="verbatim,quotes"]
----
**mv /etc/sysconfig/rhn/systemid /etc/sysconfig/rhn/disable.systemid
sed -i -e '/^enabled =/s/1/0/' /etc/yum/pluginconf.d/rhnplugin.conf**
----


== Register host with Red Hat subscription service


.Register Host
[literal,subs="verbatim,quotes"]
----
*subscription-manager register --username <username> --password <password>*
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: e3c6b7ba-83fa-4af8-8ef9-10aa6af2dd2e
The registered system name is: markllama-rhel7
----

* Check status of registration and attachement


.Check Status (before attach)
[literal,subs="verbatim,quotes"]
----
*subscription-manager status*
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Invalid

Red Hat Enterprise Linux Server:
- Not supported by a valid subscription.
----
